Tgp 2270/implement update record put in router
hmrc/trader-goods-profiles-router pull request #102
Opened 2024-08-27 09:02 UTC by pauloncast

2024-08-28 07:45 UTC, william-eyre requested changes

2024-08-28 07:45 UTC, william-eyre commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/connectors/UpdateRecordConnector.scala
I think it would be worth changing that `updateRecord` function to make it call as a `patch` method. I have put the changes in the hawk stub to have the same endpoint but be a patch

2024-08-28 09:42 UTC, pauloncast commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/connectors/UpdateRecordConnector.scala
This has been updated

2024-08-29 08:45 UTC, william-eyre approved these changes

2024-08-29 08:47 UTC, merged