Tgp 2867/update record endpoint
hmrc/trader-goods-profiles-router pull request #136
Opened 2024-11-13 10:01 UTC by kenneth-rayner

# Checklist for developers before reviewing
 - [ ] I have merged in main
 - [ ] I have assigned the PR to me
 - [ ] I have run `precheck.sh` to run all tests, format and check the code coverage
 - [ ] I have written unit test and integration tests to cover any code that I wrote, where necessary
 - [ ] I have linked tickets to any TODOs I have written
 - [ ] I have run the microservices with the latest SM2 config
 - [ ] I have checked all the Acceptance Criteria pass
 - [ ] I have run the local trader-goods-profile-api-tests
 - [ ] I have spoken to the QAs about any changes that may need to be made to the api tests OR no changes to the api tests are necessary
 - [ ] I have moved the ticket to Review in Jira
 - [ ] I have left a message in tgp-prs on slack to alert other Devs that this ticket is ready for review
 - [ ] I have checked my PR is not in draft mode

# Checklist for reviewer 1
- [ ] I have added an emoji to the relevant message in tgp-prs to show I am reviewing
- [ ] I have checked out the branch
- [ ] I have run the microservices with the latest SM2 config
- [ ] I have checked all the Acceptance Criteria pass
- [ ] I reviewed the code and left comments where necessary
- [ ] I have left a message on the relevant tgp-prs message to show that I have finished reviewing

# Checklist for reviewer 2
- [ ] I have added an emoji to the relevant message in tgp-prs to show I am reviewing
- [ ] I have checked out the branch
- [ ] I have run the microservices with the latest SM2 config
- [ ] I have checked all the Acceptance Criteria pass
- [ ] I reviewed the code and left comments where necessary
- [ ] I have left a message on the relevant tgp-prs message to show that I have finished reviewing

# Checklist for developers before merging
 - [ ] The PR has been approved by 2 other developers
 - [ ] I have merged in main
 - [ ] I have run `precheck.sh` to run all tests, check formatting and code coverage
 - [ ] I have run the microservices with the latest SM2 config
 - [ ] I have checked all the Acceptance Criteria pass
 - [ ] I have checked that the QAs have merged in any changes to the api tests
 - [ ] I have run the local trader-goods-profile-api-tests

# Reminders for developers after merging
 1. Wait for pipeline to pass
 2. Move ticket to QA column in Jira
 3. Leave message in tgp-qa on slack to alert QAs that this ticket is ready for testing

2024-11-19 16:43 UTC, besscerule commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/config/HawkInstanceConfig.scala
>          config.get[String]("update-record"),
do we need this line anymore?

2024-11-19 16:43 UTC, besscerule commented on conf/application.conf
>          update-record  = "/tgp/updaterecord/v1"
do we need this?

2024-11-20 08:45 UTC, taylors-version requested changes
Looks good other than still needing the feature flag until everything goes to prod

2024-11-20 08:45 UTC, taylors-version commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/config/AppConfig.scala
> -  lazy val useEisPatchMethod: Boolean =
This needs pulling back until EIS Patch is in Prod

2024-11-20 08:45 UTC, taylors-version commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/connectors/UpdateRecordConnector.scala
> -    if (appConfig.useEisPatchMethod) {
As mentioned, we still need this config for now

2024-11-20 08:45 UTC, taylors-version commented on conf/application.conf
> -     useEisPatchMethod = false
Still need this too

2024-11-20 16:01 UTC, kenneth-rayner commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/connectors/UpdateRecordConnector.scala
>      payload: UpdateRecordPayload,
We thought that this had to change to have the new split out bearer token. Have pushed up a small refactor.

2024-11-20 16:08 UTC, taylors-version commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/connectors/UpdateRecordConnector.scala
>      payload: UpdateRecordPayload,
I've pushed the change that I think is needed. Let's have a chat tomorrow if you think I'm wrong

2024-11-21 07:39 UTC, Reece-Carruthers commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/connectors/UpdateRecordConnector.scala
>      payload: UpdateRecordPayload,
Okay, just one thing I want to double check then is if we are sending the correct bearer tokens around, we made a new one for patch, but just want to be sure that the old one should be used for any connector call doing .put? and any doing .patch needs to use the new one?

2024-11-21 08:05 UTC, taylors-version commented on app/uk/gov/hmrc/tradergoodsprofilesrouter/connectors/UpdateRecordConnector.scala
>      payload: UpdateRecordPayload,
I have to check this one every single time. Here's the response I got from EIS:
> EIS will provide a new bearer token for new PUT request (/tgp/puttgprecord/v1). The existing bearer token should work for new PATCH request  (/tgp/update/record/v1). Hope it helps.
So the bearer token inside _our_ .patch remains the same (appConfig.hawkConfig.updateRecordUrl) and _our_ .put will use a new one.
So yea, I think the buildHeaderWithoutClientId needs to change

2024-11-21 09:08 UTC, taylors-version approved these changes

2024-11-21 09:42 UTC, taylors-version approved these changes

2024-11-21 10:32 UTC, Ewan-James-Donovan approved these changes

2024-11-21 11:49 UTC, yohan-oc approved these changes

2024-11-21 12:43 UTC, merged